version: '3'

x-mysql-variables: &mysql-variables
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_DATABASE: mydatabase
  MYSQL_USER: user
  MYSQL_PASSWORD: secret
  MYSQL_DC_HOSTNAME: bigdata-mysql

services:
  spark:
    image: bitnami/spark:latest
    container_name: bigdata-spark
    ports:
      - "7077:7077" # WORKER
      - "8181:8080" # INTERFACE: http://localhost:8181
    environment:
      - SPARK_MASTER_HOST=localhost
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4G
      - SPARK_LOCAL_DIRS=/tmp
      - SPARK_WORKER_DIR=/tmp
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=2G
      - SPARK_EXECUTOR_CORES=1
      - SPARK_NUM_EXECUTORS=1
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      - bigdata-net

  mysql:
    image: mysql:latest
    container_name: bigdata-mysql
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 500m
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/init.sql:/data/application/init.sql
    environment: *mysql-variables
    networks:
      - bigdata-net

  adminer:
    image: adminer:4.8.1-standalone
    container_name: bigdata-adminer
    ports:
      - "3333:8080" # INTERFACE: http://localhost:3333
    deploy:
      resources:
        limits:
          memory: 500m
    depends_on:
      - mysql
    networks:
      - bigdata-net

  mongodb:
    image: mongo:latest
    container_name: bigdata-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      - bigdata-net

  mongodb-compass:
    image: mongo-express:1.0.0-18-alpine3.18
    container_name: bigdata-mongodb-compass
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "root"
      ME_CONFIG_BASICAUTH_USERNAME: "root"
      ME_CONFIG_BASICAUTH_PASSWORD: "root"
    ports:
      - "8081:8081" # INTERFACE: http://localhost:8081
    deploy:
      resources:
        limits:
          memory: 500m
    depends_on:
      - mongodb
    networks:
      - bigdata-net

  jupyter:
    image: jupyter/base-notebook:x86_64-python-3.11.6
    container_name: bigdata-jupyter
    ports:
      - "8888:8888"
      - "8889:8889" # INTERFACE: http://localhost:8889
    volumes:
      - ./data/notebooks:/mnt/notebooks/
    environment:
       SPARK_MASTER: local[*]
       JUPYTER_PORT: 8889
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - bigdata-net

  cron:
    build:
      context: ./cron
      dockerfile: Dockerfile
    environment: *mysql-variables
    container_name: bigdata-cron
    ports:
      - "8080:8080"
    volumes:
      - ./cron:/cron
    networks:
      - bigdata-net
    depends_on:
      - mongodb
      - mysql

volumes:
  data:
   driver: local

networks:
  bigdata-net:
    driver: bridge